# Etapa de compilación
FROM node:18 as build

# Configuración del directorio de trabajo
WORKDIR /app

# Copiar archivos necesarios
COPY package*.json ./
COPY . .

# Instalar dependencias y compilar el proyecto
RUN npm install
RUN npm run build

# Etapa final
FROM nginx:stable-alpine

# Configurar NGINX
COPY ./nginx.conf /etc/nginx/nginx.conf

# Copiar archivos compilados al directorio de NGINX
COPY --from=build /app/dist /usr/share/nginx/html

# Exponer el puerto 80
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
