version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: DockerFile
    ports:
      - "80:80"
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: DockerFile
    ports:
      - "8000:8000"
    networks:
      - app_network
    volumes:
      - ./backend/storage:/var/www/storage
      - ./backend/bootstrap/cache:/var/www/bootstrap/cache

networks:
  app_network:
    driver: bridge
