# Usar una imagen base de Nginx
FROM nginx:alpine

# Copiar el contenido de dist/ a la carpeta de Nginx en el contenedor
COPY ./frontend/dist /usr/share/nginx/html

# Exponer el puerto 80
EXPOSE 80

# Ejecutar Nginx
CMD ["nginx", "-g", "daemon off;"]