# Dockerfile-backend
FROM php:8.2-fpm

# Instalar dependencias
RUN apt-get update && apt-get install -y \
    libzip-dev unzip git \
    && docker-php-ext-install zip pdo pdo_mysql

# Instalar Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Configurar Laravel
WORKDIR /var/www/backend
COPY backend/ /var/www/backend
RUN composer install --no-dev

# Permisos
RUN chown -R www-data:www-data /var/www/backend \
    && chmod -R 775 /var/www/backend/storage /var/www/backend/bootstrap/cache

EXPOSE 8000
CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]